Output filename, line num for Pyjinn syntax errors
Introduce antlr-based PyjinnErrorListener for lexer and parser errors.

Invalid code like this:

```
print(3 "foo")
```

now results in exceptions with error messages like this, with ">>>"
indicating the precise location of the syntax error:

```
ParseException: Syntax error at <stdin> line 1 column 8: no viable alternative at input 'print(3 "foo"'
print(3 >>>"foo")
```